name: release

on:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows, build-x86_64-w64-mingw32, build-i686-w64-mingw32]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with: 
          name: uploads
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main-linux
            main-macos
            main-windows.exe
            main-x86_64-w64-mingw32.exe
            main-i686-w64-mingw32.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: g++ -static main.cpp -o main-linux
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: main-linux
      
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: g++ main.cpp -o main-macos
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: main-macos

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: g++ -static main.cpp -o main-windows
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: main-windows.exe

  build-x86_64-w64-mingw32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        run: sudo apt-get install -y g++-mingw-w64-x86-64
      - name: Compile
        run: x86_64-w64-mingw32-g++ -static-libgcc -static-libstdc++ main.cpp -o main-x86_64-w64-mingw32
      - run: ls -fo
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: main-x86_64-w64-mingw32.exe

  build-i686-w64-mingw32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        run: sudo apt-get install -y g++-mingw-w64-i686
      - name: Compile
        run: i686-w64-mingw32-g++ -static-libgcc -static-libstdc++ main.cpp -o main-i686-w64-mingw32
      - run: ls -fo
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: main-i686-w64-mingw32.exe
